baseURL = "https://jpprice.co.uk/"
languageCode = "en-gb"
title = "Jack P Price | Technical Consultant"
theme = "timer-hugo"


# Site Menus
[menu]
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "HI, MY NAME IS JACK & I AM A"
        description = "With many years experience, I'm here to help your project realise its potential."
        btn     = true
        btnText = "Contact Me"
        btnURL  = "/contact"
        [[params.banner.flipText]]
            title   = "DEVELOPER"
        [[params.banner.flipText]]
            title   = "DEVOPS CONSULTANT"
        [[params.banner.flipText]]
            title   = "CLOUD ARCHITECT"
        [[params.banner.flipText]]
            title   = "SRE CONSULTANT"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "I'm a polyglot developer with an eye for detail and a passion for technology. I've been working in the industry for over 8 years now on an enormous range of projects, technologies, and environments - all with a proven track record of delivering."
        image   = "images/jack.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "HOW CAN I HELP YOU?"
        content = "Get in touch for a consultation on what I can do for you and your project"
        btnText = "Contact me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = true
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."
